### ISSUE TITLE
"version" no longer in filecoin api?

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/js-filecoin-api-client#63]
It looks like "version" was dropped from the go-filecoin HTTP API:

https://github.com/filecoin-project/go-filecoin/commit/ceda666240b5506ff546fccc3a19553bc276597b#diff-dae4fc5a10643edbad8f0cfc56ba71a8

I was hoping to retrieve this value from my client code via the API. I'm wondering if it can be added back to the go-filecoin HTTP api?

**Comment by jimpick** [comment]
@acruikshank Was removing version from the API intentional?

**Comment by acruikshank** [comment]
Sorry this slipped past me, @jimpick . I believe the intention was simply to allow us to check the version of the Filecoin client without needing to have the daemon running. Removing it from the HTTP api was an unintended consequence. 

We should figure out a way to make version available from the client without connecting to the daemon while still exposing version from the server. Our commands library makes this a bit tricky.

**Comment by acruikshank** [comment]
I have a fix here: https://github.com/filecoin-project/go-filecoin/pull/3059
